-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS public.app_users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default",
    full_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(50) COLLATE pg_catalog."default",
    is_email_verified boolean DEFAULT false,
    is_phone_verified boolean DEFAULT false,
    auth_provider character varying(50) COLLATE pg_catalog."default" DEFAULT 'email'::character varying,
    external_provider_id character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT app_users_pkey PRIMARY KEY (id),
    CONSTRAINT app_users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.appointments
(
    id serial NOT NULL,
    project_id uuid NOT NULL,
    app_users_id uuid NOT NULL,
    service_id integer NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    price_snapshot numeric(15, 2) NOT NULL,
    currency_snapshot character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'COP'::character varying,
    meeting_link text COLLATE pg_catalog."default",
    user_notes text COLLATE pg_catalog."default",
    admin_notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    employee_id uuid,
    CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "UserId" uuid,
    "Action" text COLLATE pg_catalog."default" NOT NULL,
    "Details" jsonb,
    "Ip" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_audit_logs" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.channels
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ProjectId" uuid NOT NULL,
    "Type" text COLLATE pg_catalog."default" NOT NULL,
    "Credentials" jsonb,
    "Verified" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_channels" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.email_verification_tokens
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "UserId" uuid NOT NULL,
    "Token" text COLLATE pg_catalog."default" NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "VerifiedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_email_verification_tokens" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.employees
(
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Username" text COLLATE pg_catalog."default" NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default" NOT NULL,
    "Role" text COLLATE pg_catalog."default" NOT NULL,
    "Area" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'General'::text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Email" text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.event_log
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ProjectId" uuid,
    "LeadId" uuid,
    "EventType" text COLLATE pg_catalog."default" NOT NULL,
    "Payload" jsonb,
    "Processed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_event_log" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.login_sessions
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "UserId" uuid NOT NULL,
    "TokenHash" text COLLATE pg_catalog."default" NOT NULL,
    "DeviceInfo" text COLLATE pg_catalog."default",
    "IpAddress" text COLLATE pg_catalog."default",
    "ExpiresAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_login_sessions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "UserId" uuid NOT NULL,
    "Token" text COLLATE pg_catalog."default" NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "UsedAt" timestamp with time zone,
    "IpAddress" text COLLATE pg_catalog."default",
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_password_reset_tokens" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.projects
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "UserId" uuid NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Industry" text COLLATE pg_catalog."default",
    "Description" text COLLATE pg_catalog."default",
    "WorkingHours" jsonb,
    "Config" jsonb,
    "Status" text COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "Subdomain" character varying(63) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_projects" PRIMARY KEY ("Id"),
    CONSTRAINT projects_subdomain_key UNIQUE ("Subdomain")
);

CREATE TABLE IF NOT EXISTS public.saas_users
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Email" text COLLATE pg_catalog."default" NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default",
    "Phone" text COLLATE pg_catalog."default",
    "Timezone" text COLLATE pg_catalog."default" NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "IsEmailVerified" boolean NOT NULL DEFAULT false,
    "AuthProvider" integer NOT NULL,
    "ExternalProviderId" text COLLATE pg_catalog."default",
    "ProfilePictureUrl" text COLLATE pg_catalog."default",
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_saas_users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.services
(
    id serial NOT NULL,
    project_id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(15, 2) NOT NULL DEFAULT 0,
    currency character varying(3) COLLATE pg_catalog."default" DEFAULT 'COP'::character varying,
    duration_minutes integer NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT services_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subscriptions
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "UserId" uuid NOT NULL,
    "Plan" text COLLATE pg_catalog."default" NOT NULL,
    "Cycle" text COLLATE pg_catalog."default" NOT NULL,
    "Price" numeric(10, 2) NOT NULL,
    "Status" text COLLATE pg_catalog."default" NOT NULL,
    "RenewalDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_subscriptions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.system_settings
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "Key" text COLLATE pg_catalog."default" NOT NULL,
    "Value" jsonb,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_system_settings" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.tags
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ProjectId" uuid NOT NULL,
    "TagName" text COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_tags" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.telegram_bot_configs
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ProjectId" uuid NOT NULL,
    "BotToken" character varying(500) COLLATE pg_catalog."default" NOT NULL,
    "BotUsername" character varying(100) COLLATE pg_catalog."default",
    "WebhookUrl" character varying(500) COLLATE pg_catalog."default",
    "N8nWebhookUrl" character varying(500) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    "WorkingHours" character varying(200) COLLATE pg_catalog."default",
    "Services" character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    "Policies" text COLLATE pg_catalog."default",
    "CustomInstructions" text COLLATE pg_catalog."default",
    "IsActive" boolean NOT NULL DEFAULT false,
    "WebhookVerified" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "LastSyncAt" timestamp with time zone,
    CONSTRAINT "PK_telegram_bot_configs" PRIMARY KEY ("Id")
);

COMMENT ON TABLE public.telegram_bot_configs
    IS 'Configuración de bots de Telegram para cada proyecto (multitenant)';

COMMENT ON COLUMN public.telegram_bot_configs."ProjectId"
    IS 'FK al proyecto (tenant) - aislamiento multitenant';

COMMENT ON COLUMN public.telegram_bot_configs."BotToken"
    IS 'Token del bot de Telegram (debe ser encriptado en aplicación)';

COMMENT ON COLUMN public.telegram_bot_configs."WebhookUrl"
    IS 'URL del webhook de Telegram - generado automáticamente por el backend';

COMMENT ON COLUMN public.telegram_bot_configs."N8nWebhookUrl"
    IS 'URL del webhook de n8n - configurado automáticamente por el backend';

COMMENT ON COLUMN public.telegram_bot_configs."IsActive"
    IS 'Indica si el bot está activo y funcionando';

COMMENT ON COLUMN public.telegram_bot_configs."WebhookVerified"
    IS 'Indica si el webhook fue verificado con Telegram API';

CREATE TABLE IF NOT EXISTS public.templates
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ProjectId" uuid,
    "Industry" text COLLATE pg_catalog."default",
    "Type" text COLLATE pg_catalog."default" NOT NULL,
    "Content" text COLLATE pg_catalog."default" NOT NULL,
    "Variables" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_templates" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.transfer_tokens
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    token character varying(512) COLLATE pg_catalog."default" NOT NULL,
    tenant character varying(128) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT transfer_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.webhooks
(
    "Id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ProjectId" uuid NOT NULL,
    "Event" text COLLATE pg_catalog."default" NOT NULL,
    "TargetUrl" text COLLATE pg_catalog."default" NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_webhooks" PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT "FK_appointments_employees_employee_id" FOREIGN KEY (employee_id)
    REFERENCES public.employees ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_appointments_employee
    ON public.appointments(employee_id);


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT fk_appointments_app_users FOREIGN KEY (app_users_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_appointments_appuser
    ON public.appointments(app_users_id);


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT fk_appointments_project FOREIGN KEY (project_id)
    REFERENCES public.projects ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_appointments_project
    ON public.appointments(project_id);


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT fk_appointments_service FOREIGN KEY (service_id)
    REFERENCES public.services (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.channels
    ADD CONSTRAINT "FK_channels_projects_ProjectId" FOREIGN KEY ("ProjectId")
    REFERENCES public.projects ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_channels_project
    ON public.channels("ProjectId");


ALTER TABLE IF EXISTS public.email_verification_tokens
    ADD CONSTRAINT "FK_email_verification_tokens_saas_users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public.saas_users ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_emailverif_user
    ON public.email_verification_tokens("UserId");


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT "FK_Employees_Projects_ProjectId" FOREIGN KEY ("ProjectId")
    REFERENCES public.projects ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_employees_project
    ON public.employees("ProjectId");


ALTER TABLE IF EXISTS public.login_sessions
    ADD CONSTRAINT "FK_login_sessions_saas_users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public.saas_users ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_user
    ON public.login_sessions("UserId");


ALTER TABLE IF EXISTS public.password_reset_tokens
    ADD CONSTRAINT "FK_password_reset_tokens_saas_users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public.saas_users ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_passreset_user
    ON public.password_reset_tokens("UserId");


ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT "FK_projects_saas_users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public.saas_users ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_projects_user
    ON public.projects("UserId");


ALTER TABLE IF EXISTS public.services
    ADD CONSTRAINT fk_project FOREIGN KEY (project_id)
    REFERENCES public.projects ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subscriptions
    ADD CONSTRAINT "FK_subscriptions_saas_users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public.saas_users ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_subscriptions_user
    ON public.subscriptions("UserId");


ALTER TABLE IF EXISTS public.tags
    ADD CONSTRAINT "FK_tags_projects_ProjectId" FOREIGN KEY ("ProjectId")
    REFERENCES public.projects ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.telegram_bot_configs
    ADD CONSTRAINT "FK_telegram_bot_configs_projects_ProjectId" FOREIGN KEY ("ProjectId")
    REFERENCES public.projects ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_telegrambotconfigs_project
    ON public.telegram_bot_configs("ProjectId");


ALTER TABLE IF EXISTS public.webhooks
    ADD CONSTRAINT "FK_webhooks_projects_ProjectId" FOREIGN KEY ("ProjectId")
    REFERENCES public.projects ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_webhooks_project
    ON public.webhooks("ProjectId");

END;